name: poke_search
description: Pokedex Search App


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  http: ^0.12.0+2
  modal_progress_hud: ^0.1.3
  floating_action_bubble: 1.0.9
  lottie: ^0.6.0
  clippy_flutter: ^1.1.1
  material_design_icons_flutter: ^4.0.5855
  flutter_svg: ^0.18.1
  gradient_widgets: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - images/
#    - allPokemons.json
    - assets/
